language: python

sudo: false

git:
  depth: 1

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_ebe4013f8360_key -iv $encrypted_ebe4013f8360_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip

before_script:
  - docker build -t nuke_my_tweets .

script:
  - docker run nuke_my_tweets
