language: c

sudo: false

git:
  depth: 1

services:
  - docker

install:
  - openssl aes-256-cbc -K $encrypted_ebe4013f8360_key -iv $encrypted_ebe4013f8360_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip

script:
  - docker build -t mmphego/nuke_my_tweets .
  - docker run --rm -ti --user mmphego mmphego/nuke_my_tweets bash script.sh
